export const EDIT_TODO = 'EDIT_TODO'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_MODE = 'EDIT_MODE'
export const ADD_MODE = 'ADD_MODE'
export const CTRL_STATUS = 'CTRL_STATUS'
export const GET_LIST = 'GET_LIST'
